name: wenia_test
description: "A Wenia test app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:

  # State management
  flutter_bloc: ^8.1.4

  # Code generation
  equatable: ^2.0.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9

  # DI
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Network
  dio: ^5.4.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

  # Local Storage
  cloud_firestore: ^4.15.4

  # Router
  go_router: ^13.2.0

  # Utils
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  retrofit_generator: ^8.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - config/

flutter_gen:
  line_length: 120
  integrations:
    flutter_svg: true
